id: P004609
initial_creation_type: ocr
source_metadata:
  id: bdr:W00KG03795
  title: འབྲི་གུང་གཏེར་སྒྲོམ་གནས་ཡིག་
  author: ''
  volumes:
    1771ab35719440ffb42ac4c405a2c858:
      image_group_id: I00KG03828
      title: ''
      volume_number: 1
      total_pages: 41
      base_file: v001.txt
