id: I6D327FA7
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T04:00:09+00:00'
last_modified: '2022-06-08T02:17:24.199413+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W00KG03795
  title: འབྲི་གུང་གཏེར་སྒྲོམ་གནས་ཡིག་
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '2731':
      image_group_id: I00KG03828
      title: ''
      total_pages: 41
      order: 1
      base_file: 2731.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
